# Template File (MS Word File) Location 
DocFileTemplatePath: .\template.doc

# The CSV Data file which will be used to generate word files
DataFilePath: .\sample.csv

# The location of output directory. A new directory will be created if it doesn't exist.'
OutputFilesPath: .\Output

# The output filename 
OutputFileName: "{First Name}_[timestamp].doc"

# The CSV file delimiter 
CsvDelimiter: ","

