name: .NET

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o ./dist --no-restore

    - name: Create Artefacts
    - uses: actions/upload-artifact@v3
      with:
        name: Author
        path: |
            ./dist
            !./dist/*.pdb

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
       draft: false
       prerelease: false
       release_name: ${{ github.ref }}
       tag_name: ${{ github.ref }}
       body_path: README.md


    - name: artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist
        asset_name: Author
        asset_content_type: application/zip